### PR TITLE
Require minimal digest algorithm dependencies.

### PR DESCRIPTION
**Pull request by davidlehn**
Trying to address concerns of https://github.com/digitalbazaar/forge/issues/468

### CODE REVIEW

**Comment by davidlehn** [comment]
Note this could also be done to `pbe.js`. There is some code that can select different algorithms. It could change to not include all by default and throw an error if an algorithm is not found. Does it make sense in that file?

Is the `md.all.js` name ok?

**Comment by dlongley** [comment]
It's fine to throw errors for people that are doing custom builds and trying to minimize included code (same goes for pbe). The name `md.all.js` is fine too. LGTM.

**Comment by dlongley** [comment]
This is a related note that a significant amount of work has already been put into a new MessageDigest API and consolidation of common code in the 0.8.x branch. I just want to make sure we don't duplicate efforts at all (I don't think we are yet, just a warning):

https://github.com/digitalbazaar/forge/blob/0.8.x/js/md.js

**Comment by davidlehn** [comment]
`pbe.js` updated now too. Will leave other use cases for specific requests or 0.8.x.

**Pull request merged**
