### PR TITLE
Add authorityKeyIdentifier x509v3 extension support (fixes #345)

### LINKED ISSUE #345: Issues implementing `authorityKeyIdentifier` extension
I'm currently trying to produce OpenVPN compatible certificates with forge, and I need the `authorityKeyIdentifier` extension. I've had some good results working on `_fillMissingExtensionFields` in `x509.js`. However I'm struggling on the `DirName` prop ([reference I'm using](http://javadoc.iaik.tugraz.at/iaik_jce/current/iaik/x509/extensions/AuthorityKeyIdentifier.html)).

Here is the code I have so far:

```
if(e.name === 'authorityKeyIdentifier' && options.cert) {
    // SYNTAX SEQUENCE
    e.value = asn1.create(asn1.Class.UNIVERSAL, asn1.Type.SEQUENCE, true, []);
    var seq = e.value.value;

    var keyIdentifier = options.cert.generateSubjectKeyIdentifier();
    seq.push(asn1.create(asn1.Class.CONTEXT_SPECIFIC, 0, false, keyIdentifier.getBytes()));

    var authorityCertIssuer = asn1.create(asn1.Class.CONTEXT_SPECIFIC, 1, true, []);
    // authorityCertIssuer.value.push(asn1.create(asn1.Class.CONTEXT_SPECIFIC, 7, false, forge.util.bytesFromIP('192.168.0.1')));
    authorityCertIssuer.value.push(asn1.create(asn1.Class.CONTEXT_SPECIFIC, 4, false, 'CN=Easy-RSA CA'));
    seq.push(authorityCertIssuer);

    seq.push(asn1.create(asn1.Class.CONTEXT_SPECIFIC, 2, false, new Buffer(options.cert.serialNumber, 'hex')));
  }
```

The issue arise with `authorityCertIssuer.value.push(asn1.create(asn1.Class.CONTEXT_SPECIFIC, 4, false, 'CN=Easy-RSA CA'));`, I get a scrambled result when I debug the certificate:

```
        X509v3 extensions:
            X509v3 Subject Key Identifier:
                74:67:90:BD:3E:5C:95:EE:0F:0F:A5:D8:D3:BE:CE:7B:39:7E:5F:46
            X509v3 Subject Alternative Name:
                URI:http://example.org/webid#me, IP Address:127.0.0.1
            X509v3 Authority Key Identifier:
                0...tg..>\.........{9~_F....CN=Easy-RSA CA....WN
```

While I'm expecting:

```
            X509v3 Authority Key Identifier: 
                keyid:88:87:77:39:14:9F:8C:4E:FE:29:F8:24:A9:8A:31:E5:BF:55:7B:A0
                DirName:/CN=Easy-RSA CA
                serial:CC:3F:3E:E2:6D:9A:57:4E
```

If I replace this line with the IP line commented above, I properly get:

```
        X509v3 extensions:
            X509v3 Subject Key Identifier:
                58:EC:31:D2:E5:05:C1:E6:8B:EF:68:DF:EC:6A:AF:B5:E7:22:2D:89
            X509v3 Subject Alternative Name:
                URI:http://example.org/webid#me, IP Address:127.0.0.1
            X509v3 Authority Key Identifier:
                keyid:58:EC:31:D2:E5:05:C1:E6:8B:EF:68:DF:EC:6A:AF:B5:E7:22:2D:89
                IP Address:192.168.0.1
                serial:11:00:57:4E
```

I'm really struggling to understand what I'm doing wrong (I'm very far from being an expert with crypto/openssl). Would gladly take any help / idea available!

PS: I'm also not sure about the `new Buffer(options.cert.serialNumber, 'hex')`, it looks like I might need to use some specific non-node helper? Do I?

### PR DESCRIPTION
**Pull request by mgcrea**
Tests are on their way (fixes #345)

### CODE REVIEW

**Comment by mgcrea** [comment]
Hum... I'm not really sure where to add the related unit tests, it looks like the tests currently rely on a single factory function `function createCertificate(options)`, but I'm not sure it would be a good idea to add the extension there.

**Comment by dlongley** [comment]
@mgcrea,

Unit tests go here:

https://github.com/digitalbazaar/forge/tree/master/nodejs/test

Probably in the `x509.js` file.

**Comment by dlongley** [comment]
Nevermind, looks like you found it.

**Comment by dlongley** [comment]
Thanks @mgcrea!

**Pull request merged**
