### PR TITLE
Bug fix invalid CRL distribution points

### PR DESCRIPTION
**Pull request by nixgadget**
- This is a bug fix to wrap the CRL Dist points in CHOICE as given in [rfc5280](https://tools.ietf.org/html/rfc5280#section-4.2.1.13)
- Otherwise it would fail cert verification: `openssl verify -CAfile <ca> <cert>`

### CODE REVIEW

**Comment by nixgadget** [comment]
Any update on this ?

**Comment by dlongley** [comment]
Landed as 8827e3d8e78071b6cb215fb8b1406af4b2cf1c3d.

**Comment by dlongley** [comment]
Thanks!

**Comment by nixgadget** [comment]
Thanks @dlongley

**Pull request closed without merging**
