### PR TITLE
FIX [x509] Certificate issuer and subject hash correctly computed

### LINKED ISSUE #875: [x509] certificate.subject.hash not computed correctly
Semi-related issue https://github.com/PeculiarVentures/PKI.js/issues/136

When constructing the subject hash, it does not match the expected output when compared to openssl's output. This also affects `certificate.issuer.hash`.

Details:

```
$ openssl x509 -in .\test.pem -ocspid
        Subject OCSP hash: 1CC2E7AF4B76D25234E12415B453B0EB7BA6A1A5
        Public key OCSP hash: 0AD4A2D62CE0B2B35E96C5D4F4A53853AEC8A26B
-----BEGIN CERTIFICATE-----
MIIFxzCCA6+gAwIBAgIQAwnFwvSSyDNZylYfimMGkDANBgkqhkiG9w0BAQsFADCB
hjELMAkGA1UEBhMCRUUxIjAgBgNVBAoMGUFTIFNlcnRpZml0c2VlcmltaXNrZXNr
dXMxITAfBgNVBAsMGFNlcnRpZml0c2VlcmltaXN0ZWVudXNlZDEXMBUGA1UEYQwO
TlRSRUUtMTA3NDcwMTMxFzAVBgNVBAMMDktMQVNTMy1TSyAyMDE2MB4XDTE3MDky
NjEzMjgzMFoXDTIyMTAyNTEzMjgzMFowfDERMA8GA1UEBRMIMTAwNjA3MDExETAP
BgNVBAgMCEhhcmp1bWFhMRAwDgYDVQQHDAdUYWxsaW5uMQswCQYDVQQGEwJFRTEU
MBIGA1UECgwLU3dlZGJhbmsgQVMxDDAKBgNVBAsMA1NHVzERMA8GA1UEAwwIRUVf
MTAyOTUwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDBfmxlG44BH34b
18vYYHW20jV0t1X32P7Dz2+kkxE3uktuL9TdASbdO7lhJR70EVJbGX9/xD5GH9n0
ALT/lG9pNXhehxPvC/mhJLdEQ4459SD0vROpTf11eaek5v/JP3w3hqsYmej8SjmN
9KYEhWVJWiVpunJ6L+OdeQdh9lZ77AWZe1KWIsyoaLRNWqmv3XffvyJ9UK1H4TmR
qb7tVJqDvtRqpCl3E8C2M14E6C/FEfm948qqnpuTB168u0k7L6KiYNR/FBCEAKmv
MQ2ynUgzn1tTR6owXb2jTvk7UsafZ/2GpjkUxMN8jegAG2yoT5uq0HrRhZ5rfX8w
sLdjtI+DAgMBAAGjggE4MIIBNDAJBgNVHRMEAjAAMEUGA1UdIAQ+MDwwMAYJKwYB
BAHOHwcDMCMwIQYIKwYBBQUHAgEWFWh0dHBzOi8vd3d3LnNrLmVlL2NwczAIBgYE
AI96AQEwEwYDVR0lBAwwCgYIKwYBBQUHAwIwHwYDVR0jBBgwFoAUrl5Y9fLy2cGO
2e9OB9t1ylDihwAwDgYDVR0PAQH/BAQDAgWgMB0GA1UdDgQWBBQK1KLWLOCys16W
xdT0pThTrsiiazB7BggrBgEFBQcBAQRvMG0wKAYIKwYBBQUHMAGGHGh0dHA6Ly9h
aWEuc2suZWUva2xhc3MzLTIwMTYwQQYIKwYBBQUHMAKGNWh0dHBzOi8vYy5zay5l
ZS9LTEFTUzMtU0tfMjAxNl9FRUNDUkNBX1NIQTM4NC5kZXIuY3J0MA0GCSqGSIb3
DQEBCwUAA4ICAQBRt1Uo2C38NZatLYWMxPD0m6luYQo14e2duE1Op/wQqQp1tacV
HXIXPtBV0K1vviIt7YSaaxXg0S0gqaCRKqU/u1hSwToQfxvP2yx6hLKeA+rlwLiY
tRXrBLYglu9j5tVM020aVptd8F91Em1ue5HP4uiOL8Cbj0d++H9ti+6429+M4iBz
EXgP8ujnQ9DY+HkdWxQIh9dMJSdbBn6zzblpuxIMNsSedKAxoOodNvjX9opdpX+/
PHYDGXy4qdpFeQD4ZzBurLe4sC4EG16rZIKqhLHeQnhN10n/bdGvAvLRhMLuchl9
8B4aJPh0AumnNfgbVWxGJ6xktUSW4fOBg2KWHG9wU5sIZqc2Vrup9+It86/bQmss
jtTprsukWPT+H27CZGy9nSLQZAxlJzd0l4pHU68YRJE0bEGUqdqj+1QXq5Xu+iNm
Z1FKDWJ9ghlDx7Fcla5podJOEaa7TesTFuuT9R+WY52cMRNwXRVjQhatue2hinvk
Wc5YPIMGyraSW3wBO6nk0gnia1Vigi1F+w2rwY6LurKSNYgzIwmxxUbtT7bamZnW
yPB0QBZmJO50DWjzTmGBFplKRIKJY8fAoMWZ5GtakVVa5v0fxDU7sS7rC66NrC1d
DxX71jecdzNHqNyrqbMfvJ7PvvqkD+TV23vwKReZGFLFlF6wsKGartl60A==
-----END CERTIFICATE-----
```

```js
const forge = require('node-forge');
const pem = '-----BEGIN CERTIFICATE-----\n' +
    'MIIFxzCCA6+gAwIBAgIQAwnFwvSSyDNZylYfimMGkDANBgkqhkiG9w0BAQsFADCB\n' +
    'hjELMAkGA1UEBhMCRUUxIjAgBgNVBAoMGUFTIFNlcnRpZml0c2VlcmltaXNrZXNr\n' +
    'dXMxITAfBgNVBAsMGFNlcnRpZml0c2VlcmltaXN0ZWVudXNlZDEXMBUGA1UEYQwO\n' +
    'TlRSRUUtMTA3NDcwMTMxFzAVBgNVBAMMDktMQVNTMy1TSyAyMDE2MB4XDTE3MDky\n' +
    'NjEzMjgzMFoXDTIyMTAyNTEzMjgzMFowfDERMA8GA1UEBRMIMTAwNjA3MDExETAP\n' +
    'BgNVBAgMCEhhcmp1bWFhMRAwDgYDVQQHDAdUYWxsaW5uMQswCQYDVQQGEwJFRTEU\n' +
    'MBIGA1UECgwLU3dlZGJhbmsgQVMxDDAKBgNVBAsMA1NHVzERMA8GA1UEAwwIRUVf\n' +
    'MTAyOTUwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDBfmxlG44BH34b\n' +
    '18vYYHW20jV0t1X32P7Dz2+kkxE3uktuL9TdASbdO7lhJR70EVJbGX9/xD5GH9n0\n' +
    'ALT/lG9pNXhehxPvC/mhJLdEQ4459SD0vROpTf11eaek5v/JP3w3hqsYmej8SjmN\n' +
    '9KYEhWVJWiVpunJ6L+OdeQdh9lZ77AWZe1KWIsyoaLRNWqmv3XffvyJ9UK1H4TmR\n' +
    'qb7tVJqDvtRqpCl3E8C2M14E6C/FEfm948qqnpuTB168u0k7L6KiYNR/FBCEAKmv\n' +
    'MQ2ynUgzn1tTR6owXb2jTvk7UsafZ/2GpjkUxMN8jegAG2yoT5uq0HrRhZ5rfX8w\n' +
    'sLdjtI+DAgMBAAGjggE4MIIBNDAJBgNVHRMEAjAAMEUGA1UdIAQ+MDwwMAYJKwYB\n' +
    'BAHOHwcDMCMwIQYIKwYBBQUHAgEWFWh0dHBzOi8vd3d3LnNrLmVlL2NwczAIBgYE\n' +
    'AI96AQEwEwYDVR0lBAwwCgYIKwYBBQUHAwIwHwYDVR0jBBgwFoAUrl5Y9fLy2cGO\n' +
    '2e9OB9t1ylDihwAwDgYDVR0PAQH/BAQDAgWgMB0GA1UdDgQWBBQK1KLWLOCys16W\n' +
    'xdT0pThTrsiiazB7BggrBgEFBQcBAQRvMG0wKAYIKwYBBQUHMAGGHGh0dHA6Ly9h\n' +
    'aWEuc2suZWUva2xhc3MzLTIwMTYwQQYIKwYBBQUHMAKGNWh0dHBzOi8vYy5zay5l\n' +
    'ZS9LTEFTUzMtU0tfMjAxNl9FRUNDUkNBX1NIQTM4NC5kZXIuY3J0MA0GCSqGSIb3\n' +
    'DQEBCwUAA4ICAQBRt1Uo2C38NZatLYWMxPD0m6luYQo14e2duE1Op/wQqQp1tacV\n' +
    'HXIXPtBV0K1vviIt7YSaaxXg0S0gqaCRKqU/u1hSwToQfxvP2yx6hLKeA+rlwLiY\n' +
    'tRXrBLYglu9j5tVM020aVptd8F91Em1ue5HP4uiOL8Cbj0d++H9ti+6429+M4iBz\n' +
    'EXgP8ujnQ9DY+HkdWxQIh9dMJSdbBn6zzblpuxIMNsSedKAxoOodNvjX9opdpX+/\n' +
    'PHYDGXy4qdpFeQD4ZzBurLe4sC4EG16rZIKqhLHeQnhN10n/bdGvAvLRhMLuchl9\n' +
    '8B4aJPh0AumnNfgbVWxGJ6xktUSW4fOBg2KWHG9wU5sIZqc2Vrup9+It86/bQmss\n' +
    'jtTprsukWPT+H27CZGy9nSLQZAxlJzd0l4pHU68YRJE0bEGUqdqj+1QXq5Xu+iNm\n' +
    'Z1FKDWJ9ghlDx7Fcla5podJOEaa7TesTFuuT9R+WY52cMRNwXRVjQhatue2hinvk\n' +
    'Wc5YPIMGyraSW3wBO6nk0gnia1Vigi1F+w2rwY6LurKSNYgzIwmxxUbtT7bamZnW\n' +
    'yPB0QBZmJO50DWjzTmGBFplKRIKJY8fAoMWZ5GtakVVa5v0fxDU7sS7rC66NrC1d\n' +
    'DxX71jecdzNHqNyrqbMfvJ7PvvqkD+TV23vwKReZGFLFlF6wsKGartl60A==\n' +
    '-----END CERTIFICATE-----';

const cert = forge.pki.certificateFromPem(pem);

console.log(cert.subject.hash); // c671c0c6ff0de2608feb6523802e3269108aa056
console.log(cert.issuer.hash); // 2a0690a322177957ad7a4a1341afe011000937f0
```

This is not the correct hash. A fairly simple fix is required, instead of attempting to construct the hash from the parts of the `RDNAttributes`, the hash should be constructed from the raw DER encoding of the entire issuer sequence.

### PR DESCRIPTION
**Pull request by dhensby**
Fixes #875 

After the patch the example from the linked issue produces the following (correct) hashes:

```
subject 1cc2e7af4b76d25234e12415b453b0eb7ba6a1a5
issuer 797cf08c18f544b716136397e74594ead5be9398
```

### CODE REVIEW

**Comment by dhensby** [comment]
I've added a test to assert the hashes are created correctly and verified these with openssl:

```
$ openssl x509 -in .\cert.pem -ocspid
        Subject OCSP hash: FD90A93E35C96CD6959F45EC60CA76FAA4CE8926
        Public key OCSP hash: E240686B3B7EFCE6B30F20A67FCD0125E51C92D1
-----BEGIN CERTIFICATE-----
MIIDZDCCAs2gAwIBAgIKQ8fjjgAAAABh3jANBgkqhkiG9w0BAQUFADBGMQswCQYD
VQQGEwJVUzETMBEGA1UEChMKR29vZ2xlIEluYzEiMCAGA1UEAxMZR29vZ2xlIElu
dGVybmV0IEF1dGhvcml0eTAeFw0xMjA2MjcxMzU5MTZaFw0xMzA2MDcxOTQzMjda
MGcxCzAJBgNVBAYTAlVTMRMwEQYDVQQIEwpDYWxpZm9ybmlhMRYwFAYDVQQHEw1N
b3VudGFpbiBWaWV3MRMwEQYDVQQKEwpHb29nbGUgSW5jMRYwFAYDVQQDEw13d3cu
Z29vZ2xlLmRlMIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCw2Hw3vNy5QMSd
0/iMCS8lwZk9lnEk2NmrJt6vGJfRGlBprtHp5lpMFMoi+x8m8EwGVxXHGp7hLyN/
gXuUjL7/DY9fxxx9l77D+sDZz7jfUfWmhS03Ra1FbT6myF8miVZFChJ8XgWzioJY
gyNdRUC9149yrXdPWrSmSVaT0+tUCwIDAQABo4IBNjCCATIwHQYDVR0lBBYwFAYI
KwYBBQUHAwEGCCsGAQUFBwMCMB0GA1UdDgQWBBTiQGhrO3785rMPIKZ/zQEl5RyS
0TAfBgNVHSMEGDAWgBS/wDDr9UMRPme6npH7/Gra42sSJDBbBgNVHR8EVDBSMFCg
TqBMhkpodHRwOi8vd3d3LmdzdGF0aWMuY29tL0dvb2dsZUludGVybmV0QXV0aG9y
aXR5L0dvb2dsZUludGVybmV0QXV0aG9yaXR5LmNybDBmBggrBgEFBQcBAQRaMFgw
VgYIKwYBBQUHMAKGSmh0dHA6Ly93d3cuZ3N0YXRpYy5jb20vR29vZ2xlSW50ZXJu
ZXRBdXRob3JpdHkvR29vZ2xlSW50ZXJuZXRBdXRob3JpdHkuY3J0MAwGA1UdEwEB
/wQCMAAwDQYJKoZIhvcNAQEFBQADgYEAVJ0qt/MBvHEPuWHeH51756qy+lBNygLA
Xp5Gq+xHUTOzRty61BR05zv142hYAGWvpvnEOJ/DI7V3QlXK8a6dQ+du97obQJJx
7ekqtfxVzmlSb23halYSoXmWgP8Tq0VUDsgsSLE7fS8JuO1soXUVKj1/6w189HL6
LsngXwZSuL0=
-----END CERTIFICATE-----
$ openssl x509 -in .\issuer.pem -ocspid
        Subject OCSP hash: D43B6713AB1A8679F0B70E169E9DF889ED387A4B
        Public key OCSP hash: BFC030EBF543113E67BA9E91FBFC6ADAE36B1224
-----BEGIN CERTIFICATE-----
MIICsDCCAhmgAwIBAgIDC2dxMA0GCSqGSIb3DQEBBQUAME4xCzAJBgNVBAYTAlVT
MRAwDgYDVQQKEwdFcXVpZmF4MS0wKwYDVQQLEyRFcXVpZmF4IFNlY3VyZSBDZXJ0
aWZpY2F0ZSBBdXRob3JpdHkwHhcNMDkwNjA4MjA0MzI3WhcNMTMwNjA3MTk0MzI3
WjBGMQswCQYDVQQGEwJVUzETMBEGA1UEChMKR29vZ2xlIEluYzEiMCAGA1UEAxMZ
R29vZ2xlIEludGVybmV0IEF1dGhvcml0eTCBnzANBgkqhkiG9w0BAQEFAAOBjQAw
gYkCgYEAye23pIucV+eEPkB9hPSP0XFjU5nneXQUr0SZMyCSjXvlKAy6rWxJfoNf
NFlOCnowzdDXxFdF7dWq1nMmzq0yE7jXDx07393cCDaob1FEm8rWIFJztyaHNWrb
qeXUWaUr/GcZOfqTGBhs3t0lig4zFEfC7wFQeeT9adGnwKziV28CAwEAAaOBozCB
oDAOBgNVHQ8BAf8EBAMCAQYwHQYDVR0OBBYEFL/AMOv1QxE+Z7qekfv8atrjaxIk
MB8GA1UdIwQYMBaAFEjmaPkr0rKV10fYIyAQTzOYkJ/UMBIGA1UdEwEB/wQIMAYB
Af8CAQAwOgYDVR0fBDMwMTAvoC2gK4YpaHR0cDovL2NybC5nZW90cnVzdC5jb20v
Y3Jscy9zZWN1cmVjYS5jcmwwDQYJKoZIhvcNAQEFBQADgYEAuIojxkiWsRF8YHde
BZqrocb6ghwYB8TrgbCoZutJqOkM0ymt9e8kTP3kS8p/XmOrmSfLnzYhLLkQYGfN
0rTw8Ktx5YtaiScRhKqOv5nwnQkhClIZmloJ0pC3+gz4fniisIWvXEyZ2VxVKfml
UUIuOss4jHg7y/j7lYe8vJD5UDI=
-----END CERTIFICATE-----
```

**Review by dlongley — APPROVED** [review]
@davidlehn -- this seems ok to me, can you confirm?

**Comment by dhensby** [comment]
Is there likely to be any movement on this?

I'm looking at providing a few other improvements to the library as I'm starting to use it fairly extensively, but it would be good to know if this (and other improvements) are likely to be taken in?

**Comment by Llorx** [comment]
Hello?

**Comment by dhensby** [comment]
@davidlehn - thanks for taking the time to look into some open issues recently - could I bring your attention to this one (full tests and it's a bit problematic that the issuer/subject hashes are not computed in a way that is congruent to openssl

**Pull request merged**
