### PR TITLE
Adding support for SubjectKeyIdentifier in PKCS#7

### PR DESCRIPTION
**Pull request by eoftedal**
See tests/nodejs-ski.js

### CODE REVIEW

**Comment by eoftedal** [comment]
Hi @dlongley. Still swamped I take it? :)

**Comment by dlongley** [comment]
Yes, @eoftedal, I'm sorry it's taking so long :(. I've got to make sure this PR will fit in nicely with some changes to support SignedData as well. I will get this in as soon as I can.

**Comment by lillesand** [comment]
Pinging @dlongley ;)

**Comment by dlongley** [comment]
Don't worry, I haven't forgotten about this PR! :)

I've finally cleared time to get SignedData support in -- this will happen mid-May. I do know that this work will have some conflicts with it and I want to have that new design in first. Once that's done, I'll fix the conflicts and merge this in. I'm really sorry for the long wait.

**Comment by lillesand** [comment]
Sounds reasonable. Thanks for updating us. Appreciate the great work you're doing here!

**Comment by eoftedal** [comment]
7 years old. Closing.

**Pull request closed without merging**
